# Sample configuration file for GNN Traffic Prediction

experiment:
  name: "Traffic Prediction Experiment"
  description: "Predicting traffic using spatial-temporal GNN"
  version: "1.0.0"
  tags: ["traffic", "gnn", "prediction"]

data:
  start_date: "2024-02-18 00:00:00"
  end_date: "2024-02-25 00:00:00"
  graph_prefix: "25022025_test"
  window_size: 24
  horizon: 6
  batch_size: 32
  days_back: 14
  stride: 1
  gap_threshold_minutes: 15
  standardize: true
  sigma_squared: 0.1
  epsilon: 0.5
  max_distance: 100.0
  tolerance_decimal_places: 6
  resampling_frequency: "15min"
  missing_value: -1.0
  bbox_coords: [
            [-1.65327, 54.93188],
            [-1.54993, 54.93188],
            [-1.54993, 55.02084],
            [-1.65327, 55.02084],
        ]

model:
  input_dim: 1
  hidden_dim: 64
  output_dim: 1
  num_layers: 2
  dropout: 0.2

training:
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 50
  patience: 10
  train_val_split: 0.8
  device: null  # Will auto-detect if null

paths:
  model_save_path: "models"
  data_cache: "data/cache"
  results_dir: "results"

visualization:
  dashboard_template: "dashboard.html"
  default_sensors_to_plot: 6
  max_sensors_in_heatmap: 50