# GNN Package Experiment Configuration

# Experiment metadata
experiment:
  name: "traffic_prediction_experiment"
  description: "Traffic prediction using STGNN on Newcastle sensor data"
  version: "1.0"
  tags: ["traffic", "stgnn", "newcastle"]

# Data configuration
data:
  start_date: "2024-02-18 00:00:00"
  end_date: "2025-02-18 00:00:00"
  graph_prefix: "25022025_test"
  window_size: 24  # Input window size (time steps)
  horizon: 6  # Prediction horizon (time steps)
  batch_size: 32
  days_back: 14  # For data fetching
  stride: 1  # Stride for time series windows
  gap_threshold_minutes: 15  # Maximum allowed gap in minutes

# Model configuration
model:
  input_dim: 1  # Traffic count is a single value
  hidden_dim: 64
  output_dim: 1
  num_layers: 2
  dropout: 0.2

# Training configuration
training:
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 50
  patience: 10  # Early stopping patience
  train_val_split: 0.8  # 80% training, 20% validation

# Paths configuration
paths:
  model_save_path: "models/stgnn_model.pth"
  data_cache: "data/test_data_1yr.pkl"
  results_dir: "results"

# Visualization configuration
visualization:
  dashboard_template: "dashboards/templates/layout.html"
  default_sensors_to_plot: 6
  max_sensors_in_heatmap: 20