site_name: My Docs

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem:

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Data Flow: data-flow.md
  - Training & Prediction: training-prediction.md
  - Command Line Interface: command-line.md

